name: install dependencies

runs:
  using: "composite"
  steps:

    - name: Checlout repo 
      uses: actions/checkout@v4.2.2
    
    - name: astral-sh/setup-uv
      id: setup-uv
      uses: astral-sh/setup-uv@v4.2.0
      with:
        python-version: 3.13.1      
        enable-cache: true
        cache-dependency-glob: |
          **/requirements*.txt
          **/uv.lock
          **/pyproject.toml

    - name: Install Python 3.13.1
      shell: bash
      run: uv python install 3.13.1

    - name: Create VENV
      run: uv venv

    - name: Install requirements
      shell: bash
      working-directory: src/
      run: |
        . ../.venv/bin/activate
        uv pip install -r pyproject.toml
      
    - name: run python script
      shell: bash
      run: |
        . .venv/bin/activate
        python3 src/main.py

    - name: Checking cache restore
      shell: bash
      if: steps.setup-uv.outputs.cache-hit == 'true'
      run: echo "Cache was restored"
              
