name: COMPOSITE

on: workflow_dispatch

jobs:
  
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2
    
      - name: Setup
        uses: ./.github/actions/install_deps
