name: COMPOSITE

on: workflow_dispatch

jobs:
  
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.2.2
    
      - name: Setup
        id: composite_step
        uses: ./.github/actions/install_deps
        with:
          python_version: 3.13.1

      - name: run python script
        run: |
          . .venv/bin/activate
          python3 src/main.py

      - name: Echo outout from composite step
        run: echo ${{ steps.composite_step.outputs.output_var }}
