name: ENVIRONMENTS

on: 
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: DEV
        type: choice
        options:
        - DEV
        - PROD

jobs:
  
  run_job:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest

    steps:

    - name: echo ENV_VAR
      run: echo ${{ vars.ENV_VAR }}

    - name: echo ENV_SECRET
      run: echo ${{ secrets.ENV_SECRET }}

    - name: echo REPO_VAR
      run: echo ${{ vars.REPO_VAR }}

    - name: echo REPO_SECRET
      run: echo ${{ secrets.REPO_SECRET }}
