name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: /var/lib/docker/overlay2
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Cache Docker images.
      uses: ScribeMD/docker-cache@0.3.7
      with:
        key: docker-${{ runner.os }}-${{ hashFiles('src/Dockerfile') }}
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./src
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}
