name: CI
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}       
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
      with:
        key: foo-docker-cache-{hash}
        restore-keys: |
          foo-docker-cache-
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%dT%H%M%S')"
    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./src
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
        tags: ghcr.io/${{ github.repository }}:${{ steps.date.outputs.date }}
