name: UV

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checlout repo 
        uses: actions/checkout@v4.2.2
      
      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v4.2.0
        with:
          python-version: 3.13.1      
          enable-cache: true
          cache-dependency-glob: |
            **/requirements*.txt
            **/uv.lock
            **/pyproject.toml

      - name: Install Python 3.13.1
        run: uv python install 3.13.1

      - name: Create VENV
        run: uv venv

      - name: Install requirements
        working-directory: src/
        run: |
          . ../.venv/bin/activate
          uv pip install -r pyproject.toml
        
      - name: run python script
        run: |
          . .venv/bin/activate
          python3 src/main.py

      - name: Checking cache restore
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
                
